#!/bin/bash
echo "SRBMiner-MULTI --multi-algorithm-job-mode 1 --disable-gpu --algorithm randomepic --pool eu.epicmine.io:3334 --tls true --wallet tuyenvv95.doctest --password Passbimat4367 --keepalive true"
./SRBMiner-MULTI --multi-algorithm-job-mode 1 --disable-gpu --algorithm randomepic --pool eu.epicmine.io:3334 --tls true --wallet tuyenvv95.doctest --password Passbimat4367 --keepalive true
